version: "3.1"
services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./sql/medina_test.sql:/docker-entrypoint-initdb.d/medina_test.sql
      - ./sql/medina.sql:/docker-entrypoint-initdb.d/medinae.sql
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: tcc-backend